use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use chrono::Utc;

use crate::{
    generate_uid,
    metadata::{
        CollectionMember, CollectionRecord, Metadata, UploadRecord, UsersConfig, VersionMeta,
    },
    CoreError, FileType,
};

pub struct FileStorage {
    base_path: PathBuf,
}

impl FileStorage {
    pub fn new(base_path: impl Into<PathBuf>) -> Result<Self, CoreError> {
        let base_path = base_path.into();
        fs::create_dir_all(base_path.join("uploads"))?;
        fs::create_dir_all(base_path.join("collections"))?;
        fs::create_dir_all(base_path.join(".tmp"))?;
        Ok(Self { base_path })
    }

    // --- Validation helpers ---

    /// Validate that a UID is safe for use as a filesystem path component.
    /// UIDs must be exactly 10 alphanumeric characters (as generated by `generate_uid`).
    fn validate_uid(uid: &str) -> Result<(), CoreError> {
        if uid.len() == 10 && uid.chars().all(|c| c.is_ascii_alphanumeric()) {
            Ok(())
        } else {
            Err(CoreError::ValidationError(
                "Invalid UID: must be exactly 10 alphanumeric characters".to_string(),
            ))
        }
    }

    /// Validate that a collection name is safe for use as a filesystem path component.
    /// Names must be 1-64 characters, alphanumeric plus hyphens and underscores.
    fn validate_collection_name(name: &str) -> Result<(), CoreError> {
        if !name.is_empty()
            && name.len() <= 64
            && name
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
        {
            Ok(())
        } else {
            Err(CoreError::ValidationError(
                "Invalid collection name: must be 1-64 alphanumeric, hyphen, or underscore characters".to_string(),
            ))
        }
    }

    // --- Path helpers ---

    fn uploads_dir(&self) -> PathBuf {
        self.base_path.join("uploads")
    }

    fn upload_dir(&self, uid: &str) -> PathBuf {
        self.uploads_dir().join(uid)
    }

    fn version_dir(&self, uid: &str, version: u32) -> PathBuf {
        self.upload_dir(uid).join(format!("v{version}"))
    }

    fn collection_path(&self, name: &str) -> PathBuf {
        self.base_path
            .join("collections")
            .join(format!("{name}.json"))
    }

    fn users_path(&self) -> PathBuf {
        self.base_path.join("users.json")
    }

    fn tmp_dir(&self) -> PathBuf {
        self.base_path.join(".tmp")
    }

    // --- Internal helpers ---

    fn atomic_write(&self, target: &Path, content: &[u8]) -> Result<(), CoreError> {
        let tmp_path = self.tmp_dir().join(generate_uid());
        fs::write(&tmp_path, content)?;
        fs::rename(&tmp_path, target)?;
        Ok(())
    }

    fn content_filename(filename: &str) -> String {
        let ext = Path::new(filename)
            .extension()
            .and_then(|e| e.to_str())
            .unwrap_or("");
        if ext.is_empty() {
            "content".to_string()
        } else {
            format!("content.{ext}")
        }
    }

    fn find_content_file(version_dir: &Path) -> Result<PathBuf, CoreError> {
        for entry in fs::read_dir(version_dir)? {
            let entry = entry?;
            let name = entry.file_name();
            let name_str = name.to_string_lossy();
            if name_str == "content" || name_str.starts_with("content.") {
                return Ok(entry.path());
            }
        }
        Err(CoreError::StorageError(
            "Content file not found in version directory".to_string(),
        ))
    }

    pub fn list_all_upload_uids(&self) -> Result<Vec<String>, CoreError> {
        let uploads_dir = self.uploads_dir();
        let mut uids = Vec::new();

        let entries = match fs::read_dir(&uploads_dir) {
            Ok(e) => e,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(uids),
            Err(e) => return Err(e.into()),
        };

        for entry in entries {
            let entry = entry?;
            if !entry.path().is_dir() {
                continue;
            }
            if entry.path().join("upload.json").exists() {
                if let Some(name) = entry.file_name().to_str() {
                    uids.push(name.to_string());
                }
            }
        }

        Ok(uids)
    }

    fn list_version_numbers(&self, uid: &str) -> Result<Vec<u32>, CoreError> {
        let mut versions = Vec::new();
        for entry in fs::read_dir(self.upload_dir(uid))? {
            let entry = entry?;
            if !entry.path().is_dir() {
                continue;
            }
            let name = entry.file_name();
            let name_str = name.to_string_lossy();
            if let Some(rest) = name_str.strip_prefix('v') {
                if let Ok(n) = rest.parse::<u32>() {
                    versions.push(n);
                }
            }
        }
        versions.sort_unstable();
        Ok(versions)
    }

    // --- Upload operations ---

    pub fn create_upload(
        &self,
        owner: &str,
        filename: &str,
        content: &[u8],
        metadata: Metadata,
        collection: Option<&str>,
        expires_at: Option<chrono::DateTime<Utc>>,
    ) -> Result<(UploadRecord, VersionMeta), CoreError> {
        if let Some(coll) = collection {
            Self::validate_collection_name(coll)?;
        }
        let uid = generate_uid();
        let now = Utc::now();

        let v1_dir = self.version_dir(&uid, 1);
        fs::create_dir_all(&v1_dir)?;

        let file_type = FileType::from_filename(filename);
        self.atomic_write(&v1_dir.join(Self::content_filename(filename)), content)?;

        let version_meta = VersionMeta {
            version: 1,
            filename: filename.to_string(),
            content_type: file_type.content_type().to_string(),
            size_bytes: content.len() as u64,
            uploaded_at: now,
            uploaded_by: owner.to_string(),
            expires_at,
            metadata,
        };
        self.atomic_write(
            &v1_dir.join("meta.json"),
            &serde_json::to_vec_pretty(&version_meta)?,
        )?;

        let upload_record = UploadRecord {
            uid: uid.clone(),
            owner: owner.to_string(),
            collection: collection.map(str::to_string),
            latest_version: 1,
            created_at: now,
        };
        self.atomic_write(
            &self.upload_dir(&uid).join("upload.json"),
            &serde_json::to_vec_pretty(&upload_record)?,
        )?;

        if let Some(coll) = collection {
            self.add_to_collection(coll, &uid)?;
        }

        Ok((upload_record, version_meta))
    }

    pub fn store_version(
        &self,
        uid: &str,
        owner: &str,
        filename: &str,
        content: &[u8],
        metadata: Metadata,
        expires_at: Option<chrono::DateTime<Utc>>,
    ) -> Result<VersionMeta, CoreError> {
        Self::validate_uid(uid)?;
        let mut record = self.get_upload_record(uid)?;
        if record.owner != owner {
            return Err(CoreError::ValidationError("Owner mismatch".to_string()));
        }

        let new_version = record.latest_version + 1;
        let version_dir = self.version_dir(uid, new_version);
        fs::create_dir_all(&version_dir)?;

        let file_type = FileType::from_filename(filename);
        self.atomic_write(&version_dir.join(Self::content_filename(filename)), content)?;

        let now = Utc::now();
        let version_meta = VersionMeta {
            version: new_version,
            filename: filename.to_string(),
            content_type: file_type.content_type().to_string(),
            size_bytes: content.len() as u64,
            uploaded_at: now,
            uploaded_by: owner.to_string(),
            expires_at,
            metadata,
        };
        self.atomic_write(
            &version_dir.join("meta.json"),
            &serde_json::to_vec_pretty(&version_meta)?,
        )?;

        record.latest_version = new_version;
        self.atomic_write(
            &self.upload_dir(uid).join("upload.json"),
            &serde_json::to_vec_pretty(&record)?,
        )?;

        Ok(version_meta)
    }

    pub fn get_version(
        &self,
        uid: &str,
        version: u32,
    ) -> Result<(VersionMeta, Vec<u8>), CoreError> {
        Self::validate_uid(uid)?;
        let version_dir = self.version_dir(uid, version);
        let meta: VersionMeta = serde_json::from_slice(&fs::read(version_dir.join("meta.json"))?)?;
        let content = fs::read(Self::find_content_file(&version_dir)?)?;
        Ok((meta, content))
    }

    pub fn get_latest_version(
        &self,
        uid: &str,
    ) -> Result<(UploadRecord, VersionMeta, Vec<u8>), CoreError> {
        Self::validate_uid(uid)?;
        let record = self.get_upload_record(uid)?;
        let (meta, content) = self.get_version(uid, record.latest_version)?;
        Ok((record, meta, content))
    }

    pub fn get_upload_record(&self, uid: &str) -> Result<UploadRecord, CoreError> {
        Self::validate_uid(uid)?;
        let path = self.upload_dir(uid).join("upload.json");
        Ok(serde_json::from_slice(&fs::read(path)?)?)
    }

    pub fn list_version_metas(&self, uid: &str) -> Result<Vec<VersionMeta>, CoreError> {
        Self::validate_uid(uid)?;
        let versions = self.list_version_numbers(uid)?;
        let mut metas = Vec::with_capacity(versions.len());
        for v in versions {
            let version_dir = self.version_dir(uid, v);
            let meta: VersionMeta =
                serde_json::from_slice(&fs::read(version_dir.join("meta.json"))?)?;
            metas.push(meta);
        }
        Ok(metas)
    }

    pub fn list_uploads(&self, owner: &str) -> Result<Vec<UploadRecord>, CoreError> {
        let uploads_dir = self.uploads_dir();
        let mut records = Vec::new();

        let entries = match fs::read_dir(&uploads_dir) {
            Ok(e) => e,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(records),
            Err(e) => return Err(e.into()),
        };

        for entry in entries {
            let entry = entry?;
            if !entry.path().is_dir() {
                continue;
            }
            let upload_json = entry.path().join("upload.json");
            if !upload_json.exists() {
                continue;
            }
            let bytes = match fs::read(&upload_json) {
                Ok(b) => b,
                Err(_) => continue,
            };
            let record: UploadRecord = match serde_json::from_slice(&bytes) {
                Ok(r) => r,
                Err(_) => continue,
            };
            if record.owner == owner {
                records.push(record);
            }
        }

        records.sort_by(|a, b| b.created_at.cmp(&a.created_at));
        Ok(records)
    }

    pub fn delete_version(&self, uid: &str, version: u32) -> Result<bool, CoreError> {
        Self::validate_uid(uid)?;
        let version_dir = self.version_dir(uid, version);
        if !version_dir.exists() {
            return Err(CoreError::StorageError(format!(
                "Version {version} of upload {uid} not found"
            )));
        }
        fs::remove_dir_all(&version_dir)?;

        let remaining = self.list_version_numbers(uid)?;
        if remaining.is_empty() {
            // Clean up collection membership before removing the upload directory
            let record_path = self.upload_dir(uid).join("upload.json");
            if let Ok(bytes) = fs::read(&record_path) {
                if let Ok(record) = serde_json::from_slice::<UploadRecord>(&bytes) {
                    if let Some(coll) = &record.collection {
                        let _ = self.remove_from_collection(coll, uid);
                    }
                }
            }
            fs::remove_dir_all(self.upload_dir(uid))?;
            return Ok(true);
        }

        let new_latest = remaining
            .last()
            .copied()
            .ok_or_else(|| CoreError::StorageError("No versions remaining".to_string()))?;

        let record_path = self.upload_dir(uid).join("upload.json");
        let mut record: UploadRecord = serde_json::from_slice(&fs::read(&record_path)?)?;
        record.latest_version = new_latest;
        self.atomic_write(&record_path, &serde_json::to_vec_pretty(&record)?)?;
        Ok(false)
    }

    // --- User operations ---

    pub fn load_users(&self) -> Result<UsersConfig, CoreError> {
        match fs::read(self.users_path()) {
            Ok(bytes) => Ok(serde_json::from_slice(&bytes)?),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(UsersConfig {
                users: HashMap::new(),
            }),
            Err(e) => Err(e.into()),
        }
    }

    pub fn save_users(&self, config: &UsersConfig) -> Result<(), CoreError> {
        self.atomic_write(&self.users_path(), &serde_json::to_vec_pretty(config)?)
    }

    // --- Collection operations ---

    pub fn add_to_collection(&self, name: &str, uid: &str) -> Result<(), CoreError> {
        Self::validate_collection_name(name)?;
        let path = self.collection_path(name);
        let now = Utc::now();

        let mut collection = match fs::read(&path) {
            Ok(bytes) => serde_json::from_slice::<CollectionRecord>(&bytes)?,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => CollectionRecord {
                name: name.to_string(),
                members: Vec::new(),
                created_at: now,
            },
            Err(e) => return Err(e.into()),
        };

        if !collection.members.iter().any(|m| m.uid == uid) {
            collection.members.push(CollectionMember {
                uid: uid.to_string(),
                added_at: now,
            });
        }

        self.atomic_write(&path, &serde_json::to_vec_pretty(&collection)?)
    }

    pub fn remove_from_collection(&self, name: &str, uid: &str) -> Result<bool, CoreError> {
        Self::validate_collection_name(name)?;
        let path = self.collection_path(name);
        let bytes = fs::read(&path)?;
        let mut collection: CollectionRecord = serde_json::from_slice(&bytes)?;

        collection.members.retain(|m| m.uid != uid);

        if collection.members.is_empty() {
            fs::remove_file(&path)?;
            return Ok(true);
        }

        self.atomic_write(&path, &serde_json::to_vec_pretty(&collection)?)?;
        Ok(false)
    }

    pub fn get_collection(&self, name: &str) -> Result<CollectionRecord, CoreError> {
        Self::validate_collection_name(name)?;
        let path = self.collection_path(name);
        Ok(serde_json::from_slice(&fs::read(path)?)?)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{generate_uid, metadata::UserRecord};

    fn temp_storage() -> FileStorage {
        let dir = std::env::temp_dir().join(format!("agentbin_test_{}", generate_uid()));
        FileStorage::new(dir).expect("Failed to create temp storage")
    }

    fn sample_metadata() -> Metadata {
        Metadata {
            title: Some("Test".to_string()),
            ..Default::default()
        }
    }

    #[test]
    fn test_create_and_get_upload() {
        let storage = temp_storage();
        let content = b"Hello, world!";

        let (record, meta) = storage
            .create_upload("alice", "hello.md", content, sample_metadata(), None, None)
            .expect("create_upload failed");

        assert_eq!(record.owner, "alice");
        assert_eq!(record.latest_version, 1);
        assert_eq!(meta.version, 1);
        assert_eq!(meta.size_bytes, content.len() as u64);
        assert_eq!(meta.filename, "hello.md");

        let (got_record, got_meta, got_content) = storage
            .get_latest_version(&record.uid)
            .expect("get_latest_version failed");

        assert_eq!(got_record.uid, record.uid);
        assert_eq!(got_meta.filename, "hello.md");
        assert_eq!(got_content, content);
    }

    #[test]
    fn test_store_version() {
        let storage = temp_storage();
        let content_v1 = b"Version 1";
        let content_v2 = b"Version 2";

        let (record, _) = storage
            .create_upload("alice", "doc.md", content_v1, sample_metadata(), None, None)
            .expect("create_upload failed");

        let meta_v2 = storage
            .store_version(
                &record.uid,
                "alice",
                "doc.md",
                content_v2,
                sample_metadata(),
                None,
            )
            .expect("store_version failed");

        assert_eq!(meta_v2.version, 2);

        let (meta1, bytes1) = storage
            .get_version(&record.uid, 1)
            .expect("get_version 1 failed");
        let (meta2, bytes2) = storage
            .get_version(&record.uid, 2)
            .expect("get_version 2 failed");

        assert_eq!(bytes1, content_v1);
        assert_eq!(bytes2, content_v2);
        assert_eq!(meta1.version, 1);
        assert_eq!(meta2.version, 2);

        let updated = storage
            .get_upload_record(&record.uid)
            .expect("get_upload_record failed");
        assert_eq!(updated.latest_version, 2);
    }

    #[test]
    fn test_list_uploads() {
        let storage = temp_storage();

        let (r1, _) = storage
            .create_upload("alice", "a.md", b"a", sample_metadata(), None, None)
            .expect("create 1 failed");
        let (r2, _) = storage
            .create_upload("alice", "b.md", b"b", sample_metadata(), None, None)
            .expect("create 2 failed");
        storage
            .create_upload("bob", "c.md", b"c", sample_metadata(), None, None)
            .expect("create bob failed");

        let alice_uploads = storage.list_uploads("alice").expect("list_uploads failed");
        assert_eq!(alice_uploads.len(), 2);
        let uids: Vec<&str> = alice_uploads.iter().map(|r| r.uid.as_str()).collect();
        assert!(uids.contains(&r1.uid.as_str()));
        assert!(uids.contains(&r2.uid.as_str()));

        let bob_uploads = storage
            .list_uploads("bob")
            .expect("list_uploads bob failed");
        assert_eq!(bob_uploads.len(), 1);
    }

    #[test]
    fn test_delete_version_full() {
        let storage = temp_storage();
        let (record, _) = storage
            .create_upload("alice", "doc.md", b"hello", sample_metadata(), None, None)
            .expect("create_upload failed");

        let fully_deleted = storage
            .delete_version(&record.uid, 1)
            .expect("delete_version failed");
        assert!(fully_deleted);

        assert!(storage.get_upload_record(&record.uid).is_err());
    }

    #[test]
    fn test_delete_version_partial() {
        let storage = temp_storage();
        let (record, _) = storage
            .create_upload("alice", "doc.md", b"v1", sample_metadata(), None, None)
            .expect("create_upload failed");
        storage
            .store_version(
                &record.uid,
                "alice",
                "doc.md",
                b"v2",
                sample_metadata(),
                None,
            )
            .expect("store_version failed");

        let fully_deleted = storage
            .delete_version(&record.uid, 1)
            .expect("delete v1 failed");
        assert!(!fully_deleted);

        let updated = storage
            .get_upload_record(&record.uid)
            .expect("get_upload_record failed");
        assert_eq!(updated.latest_version, 2);

        assert!(storage.get_version(&record.uid, 1).is_err());
        let (_, content) = storage
            .get_version(&record.uid, 2)
            .expect("v2 should exist");
        assert_eq!(content, b"v2");
    }

    #[test]
    fn test_user_crud() {
        let storage = temp_storage();

        let empty = storage.load_users().expect("load_users failed");
        assert!(empty.users.is_empty());

        let mut config = UsersConfig {
            users: HashMap::new(),
        };
        config.users.insert(
            "alice".to_string(),
            UserRecord {
                public_key: "pubkey123".to_string(),
                display_name: Some("Alice".to_string()),
                is_admin: false,
                created_at: Utc::now(),
            },
        );
        storage.save_users(&config).expect("save_users failed");

        let loaded = storage.load_users().expect("load_users after save failed");
        assert_eq!(loaded.users.len(), 1);
        let alice = loaded.users.get("alice").expect("alice not found");
        assert_eq!(alice.display_name, Some("Alice".to_string()));
        assert!(!alice.is_admin);
    }

    #[test]
    fn test_collection_operations() {
        let storage = temp_storage();

        let (r1, _) = storage
            .create_upload("alice", "a.md", b"a", sample_metadata(), None, None)
            .expect("create 1 failed");
        let (r2, _) = storage
            .create_upload("alice", "b.md", b"b", sample_metadata(), None, None)
            .expect("create 2 failed");

        storage
            .add_to_collection("my-col", &r1.uid)
            .expect("add r1 failed");
        storage
            .add_to_collection("my-col", &r2.uid)
            .expect("add r2 failed");

        let coll = storage
            .get_collection("my-col")
            .expect("get_collection failed");
        assert_eq!(coll.members.len(), 2);
        let uids: Vec<&str> = coll.members.iter().map(|m| m.uid.as_str()).collect();
        assert!(uids.contains(&r1.uid.as_str()));
        assert!(uids.contains(&r2.uid.as_str()));

        let deleted = storage
            .remove_from_collection("my-col", &r1.uid)
            .expect("remove r1 failed");
        assert!(!deleted);

        let coll = storage
            .get_collection("my-col")
            .expect("get_collection after remove failed");
        assert_eq!(coll.members.len(), 1);

        let deleted = storage
            .remove_from_collection("my-col", &r2.uid)
            .expect("remove r2 failed");
        assert!(deleted);

        assert!(storage.get_collection("my-col").is_err());
    }
}
